 platform :ios, '9.0'

target 'Travel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travel

pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SVProgressHUD'
pod 'Alamofire'
pod 'SwiftyJSON'

  target 'TravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
